#ifndef _CLOUDDEF_20230412_
#define _CLOUDDEF_20230412_
#include <iostream>
typedef enum eCLOUDMODE
{
	eCLOUDMODE_NONE = 0,
	eCLOUDMODE_TEMPLATE = 1,
	eCLOUDMODE_CLOUD = 2,
	eCLOUDMODE_HMI = 3,
	eCLOUDMODE_MAX
} eCLOUDMODE_T;

enum DATA_TYPE {
	REAL_CONFIGS = 0,
	HIS_CONFIGS = 1,
	ALARM_CONFIGS = 2,
};

enum REAL_TYPE {
	REPORT_CONFIG = 0,
	SWITCH_CONFIG = 1,
};
#endif // _CLOUD_20230412_